import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const LanguageContext = createContext();

export const languages = {
  en: { code: 'en', label: 'English', flag: 'EN', dir: 'ltr' },
  fr: { code: 'fr', label: 'Français', flag: 'FR', dir: 'ltr' },
  ar: { code: 'ar', label: 'العربية', flag: 'ع', dir: 'rtl' },
};

export const categoryLabels = {
  en: {
    fuel_purchase: 'Fuel Purchase',
    salary: 'Workers Salary',
    water_electricity: 'Water & Electricity',
    cleaning_products: 'Cleaning Products',
    rent: 'Rent',
    maintenance: 'Maintenance',
    other: 'Other',
    fuel_sales: 'Fuel Sales',
    shop_sales: 'Convenience Store',
    services: 'Car Wash & Services',
  },
  fr: {
    fuel_purchase: 'Achat de Carburant',
    salary: 'Salaire des Ouvriers',
    water_electricity: 'Eau & Électricité',
    cleaning_products: 'Produits de Nettoyage',
    rent: 'Loyer',
    maintenance: 'Entretien',
    other: 'Autre',
    fuel_sales: 'Vente de Carburant',
    shop_sales: 'Boutique',
    services: 'Lavage & Services',
  },
  ar: {
    fuel_purchase: 'شراء الوقود',
    salary: 'رواتب العمال',
    water_electricity: 'الماء والكهرباء',
    cleaning_products: 'مواد التنظيف',
    rent: 'الإيجار',
    maintenance: 'الصيانة',
    other: 'أخرى',
    fuel_sales: 'مبيعات الوقود',
    shop_sales: 'المتجر',
    services: 'الغسيل والخدمات',
  },
};

export const t = {
  en: {
    // Brand
    brandName: 'Al Mohit Gas Station',
    brandTagline: 'Operations Portal',
    // Nav
    dashboard: 'Dashboard',
    financials: 'Financial Ledger',
    staff: 'Staff & Payroll',
    reviewQueue: 'Review Queue',
    soldGas: 'Sold Gas',
    logout: 'Sign Out',
    // Login
    loginTitle: 'Sign In',
    loginSubtitle: 'Station Management Portal',
    email: 'Email Address',
    password: 'Password',
    signIn: 'Sign In',
    authorizedOnly: 'Authorized personnel only',
    fillCredentials: 'Please fill in all credentials fields.',
    invalidCredentials: 'Invalid email or password.',
    // Dashboard
    execDashboard: 'Executive Dashboard',
    dashboardDesc: 'Live operational overview, financial analytics & ledger comparisons.',
    smartScan: 'Smart Scan',
    exportData: 'Export Data',
    reviewRequired: 'Receipt Review Action Required',
    reviewRequiredDesc: 'There are {n} low-confidence scanned receipts awaiting manual verification.',
    resolveQueue: 'Resolve Queue',
    weekView: 'Week',
    monthView: 'Month',
    yearView: 'Year',
    refresh: 'Refresh Data',
    totalRevenue: 'Total Sales Revenue',
    totalSpend: 'Total Operating Spend',
    netProfit: 'Net Operating Profit',
    receiptsSales: '+ Receipts & sales',
    chargesLogistics: '- Charges & logistics',
    surplus: 'Surplus recorded',
    deficit: 'Operating deficit',
    trendTitle: 'Revenue vs. Operating Spend Trend',
    trendDesc: 'Chronological flow comparing cash inflows against expenses.',
    noHistory: 'No historical entries recorded within this range.',
    revenueDist: 'Revenue Stream Distributions',
    revenueDistDesc: 'Breakdown of earnings by service category streams.',
    noRevenueData: 'No revenue data available.',
    expenseDist: 'Expense Category Distributions',
    expenseDistDesc: 'Categorization of charges ledger transactions.',
    noExpenseData: 'No operating expense data available.',
    vendorBreakdown: 'Vendor Spend Breakdown',
    vendorBreakdownDesc: 'Operating charges grouped by fuel supplier.',
    recentTransactions: 'Recent Transactions',
    recentTransactionsDesc: 'Latest recorded ledger entries.',
    aggregating: 'Aggregating records and compiling analytics...',
    failedDashboard: 'Failed to Load Dashboard',
    retryConnection: 'Retry Connection',
    // Financials
    financialLedger: 'Financial Ledgers',
    financialsDesc: 'Track company logs, supplier receipts, and daily sales streams.',
    addCharge: 'Add Operating Charge',
    logRevenue: 'Log Sales Revenue',
    tabCharges: 'Operating Expenses / Charges',
    tabRevenue: 'Sales Revenue Streams',
    ledgerTotal: 'Current Ledger Total',
    ledgerTotalDesc: 'Sum value of all listed items matching active filters.',
    searchFilters: 'Search Filters',
    clearAll: 'Clear All',
    category: 'Category',
    allCategories: 'All Categories',
    allSources: 'All Sources',
    fuelVendor: 'Fuel Vendor',
    allSuppliers: 'All Suppliers',
    startDate: 'Start Date',
    endDate: 'End Date',
    date: 'Date',
    supplierVendor: 'Supplier Vendor',
    description: 'Description',
    flowType: 'Flow Type',
    amount: 'Amount (MAD / DH)',
    actions: 'Actions',
    ocrScan: 'OCR Scan',
    manual: 'Manual',
    salesInflow: 'Sales Inflow',
    noCharges: 'No matching expense logs found.',
    noRevenue: 'No matching revenue logs found.',
    retrieving: 'Retrieving transactions ledger...',
    recordCharge: 'Record Expense Charge',
    logRevenueStream: 'Log Daily Revenue Stream',
    editEntry: 'Edit Ledger Entry',
    valueAmount: 'Value Amount (MAD / DH)',
    transactionDate: 'Transaction Date',
    categoryClassification: 'Category Classification',
    selectCategory: 'Select Category...',
    selectStream: 'Select Stream...',
    supplierMapping: 'Supplier Vendor mapping',
    chooseSupplier: 'Choose Supplier...',
    notesRemarks: 'Notes / Remarks',
    notesPlaceholder: 'Reference invoice/transaction notes...',
    cancel: 'Cancel',
    confirmEntry: 'Confirm Entry',
    save: 'Save',
    deleteConfirm: 'Are you sure you want to permanently delete this financial record?',
    // Workers
    staffPayroll: 'Staff & Payroll',
    staffDesc: 'Manage station staff, CIN records, and salary payments.',
    addStaff: 'Add Staff',
    logPayment: 'Log Payment',
    roster: 'Station Roster',
    payroll: 'Payroll',
    name: 'Name',
    cin: 'CIN',
    position: 'Position',
    phone: 'Phone',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    fullName: 'Full Name',
    cinLabel: 'CIN (National ID)',
    hireDate: 'Hire Date',
    modifyStaff: 'Modify Staff Profile',
    registerStaff: 'Register New Staff',
    selectWorker: 'Select Worker',
    selectPosition: 'Select...',
    pumpAttendant: 'Pump Attendant',
    cashier: 'Cashier',
    technician: 'Technician',
    paymentAmount: 'Amount (MAD / DH)',
    paymentDate: 'Payment Date',
    paymentNotes: 'Notes',
    paymentNotesPlaceholder: 'Weekly pay, overtime, bonus...',
    logSalaryPayment: 'Log Salary Payment',
    logPaymentBtn: 'Log Payment',
    noPayments: 'No payments logged.',
    deletePaymentConfirm: 'Delete this payment and its linked charge?',
    // Review Queue
    reviewQueueTitle: 'Receipt Review Queue',
    reviewQueueDesc: 'Audit low-confidence scans or unidentified supplier receipts here before filing them to the ledger.',
    loadingQueue: 'Loading pending receipt audit queue...',
    queueClear: 'Queue Clear!',
    queueClearDesc: 'All scanned receipts are successfully resolved, categorized, and recorded.',
    pendingTickets: 'Pending Tickets',
    unknownVendor: 'Unknown Vendor',
    matchPct: '% Match',
    uploaded: 'Uploaded',
    amountNA: 'Amount: N/A',
    auditForm: 'Audit Settlement Form',
    auditFormDesc: 'Reconcile OCR extractions with visual proof.',
    verifyAmount: 'Verify Amount (MAD / DH)',
    assignVendor: 'Assign Vendor',
    unassigned: 'Unassigned (Set Supplier...)',
    receiptDate: 'Receipt Date',
    filingCategory: 'Filing Category',
    reject: 'Reject',
    approveLedger: 'Approve Ledger',
    // Scanner
    receiptEntry: 'Receipt Entry',
    aiScan: 'AI Scan',
    manualEntry: 'Manual Entry',
    scanning: 'Vertex AI is reading receipt...',
    scanningDesc: 'Extracting vendor, totals, and date via Gemini 2.5 Flash',
    useCamera: 'Use Camera',
    analyzeAI: 'Analyze with AI',
    dragDrop: 'Drag & drop receipt or click to browse',
    fileTypes: 'PNG, JPG, WEBP, PDF (Max 10MB)',
    vendor: 'Vendor',
    selectVendor: 'Select vendor...',
    addAnother: 'Add Another',
    entryFailed: 'Entry Failed',
    tryAgain: 'Try Again',
    filedSuccess: 'Filed Successfully!',
    sentToReview: 'Sent to Review',
    fileReceipt: 'File Receipt',
    filing: 'Filing...',
    receiptImage: 'Receipt Image (Optional)',
    amountDateRequired: 'Amount and date are required.',
    cameraFailed: 'Could not access camera. Please upload an image file instead.',
    verifyAndFile: 'Verify & File to Ledger',
    // Sold Gas
    soldGasDesc: 'Upload multiple sold-gas receipts, let AI read amount/date/vendor, then approve each one to log as fuel sales revenue.',
    processingReceipts: 'AI is reading your receipts...',
    soldGasDrop: 'Drag & drop multiple receipts or click to select from gallery',
    soldGasFileTypes: 'PNG, JPG, WEBP, PDF — Select up to 20 (Max 10MB each)',
    receiptsSelected: 'receipts selected',
    scanAll: 'Scan All with AI',
    processedOk: 'scanned successfully',
    processedFailed: 'failed',
    soldGasQueueClear: 'No Receipts to Approve',
    soldGasQueueClearDesc: 'Upload sold-gas receipts above. After AI reads them, approve each one to record as fuel sales.',
    reviewing: 'Reviewing',
    of: 'of',
    approveSoldGas: 'Approve & Next',
    soldGasApproveTitle: 'Approve Sold Gas Receipt',
    soldGasApproveDesc: 'Verify the extracted amount, date, and vendor, then approve to log as fuel sales revenue.',
    ocrResults: 'OCR Extracted Data',
    ocrResultsDesc: 'Review and correct the extracted fields, then file to the ledger.',
    confirmFile: 'Confirm & File',
    savePending: 'Save as Pending Review',
    confidence: 'Confidence',
    // Export
    exportTitle: 'Export Financial Statement',
    exportFormat: 'Export Format',
    microsoftExcel: 'Microsoft Excel',
    pdfStatement: 'PDF Statement',
    exportScope: 'Export Scope',
    combinedStatement: 'Combined Statement (Dashboard + Revenue + Expenses + Receipts)',
    revenueOnly: 'Revenue Stream Ledger Only',
    chargesOnly: 'Operating Expenses Only',
    receiptsOnly: 'Scanned Receipts Logs & Audit Trail Only',
    timeInterval: 'Time Interval',
    custom: 'Custom',
    customDatesRequired: 'Please specify both Start Date and End Date for custom filters.',
    exportFailed: 'Failed to trigger file download. Please try again.',
    generating: 'Generating...',
    exportTo: 'Export to',
    vendorFilter: 'Vendor Filter',
    categoryFilter: 'Category Filter',
    allVendors: 'All Vendors',
    // Misc
    loading: 'Loading...',
  },
  fr: {
    brandName: 'Station-service Al Mohit',
    brandTagline: 'Portail Opérations',
    dashboard: 'Tableau de Bord',
    financials: 'Grand Livre Financier',
    staff: 'Personnel & Paie',
    reviewQueue: 'File de Révision',
    soldGas: 'Ventes Carburant',
    logout: 'Se Déconnecter',
    loginTitle: 'Se Connecter',
    loginSubtitle: 'Portail de Gestion de Station',
    email: 'Adresse E-mail',
    password: 'Mot de Passe',
    signIn: 'Se Connecter',
    authorizedOnly: 'Personnel autorisé uniquement',
    fillCredentials: 'Veuillez remplir tous les champs.',
    invalidCredentials: 'E-mail ou mot de passe invalide.',
    execDashboard: 'Tableau de Bord Exécutif',
    dashboardDesc: 'Vue opérationnelle en direct, analytique financière et comparaisons.',
    smartScan: 'Numérisation IA',
    exportData: 'Exporter',
    reviewRequired: 'Action de Révision Requise',
    reviewRequiredDesc: 'Il y a {n} reçus à faible confiance en attente de vérification.',
    resolveQueue: 'Résoudre la File',
    weekView: 'Semaine',
    monthView: 'Mois',
    yearView: 'Année',
    refresh: 'Actualiser',
    totalRevenue: 'Revenus Totaux',
    totalSpend: 'Dépenses d\'Exploitation',
    netProfit: 'Bénéfice Net',
    receiptsSales: '+ Reçus & ventes',
    chargesLogistics: '- Charges & logistique',
    surplus: 'Excédent enregistré',
    deficit: 'Déficit d\'exploitation',
    trendTitle: 'Tendance Revenus vs. Dépenses',
    trendDesc: 'Flux chronologique comparant entrées et sorties.',
    noHistory: 'Aucune entrée enregistrée dans cette période.',
    revenueDist: 'Répartition des Revenus',
    revenueDistDesc: 'Ventilation des gains par catégorie.',
    noRevenueData: 'Aucune donnée de revenu.',
    expenseDist: 'Répartition des Dépenses',
    expenseDistDesc: 'Catégorisation des charges.',
    noExpenseData: 'Aucune dépense d\'exploitation.',
    vendorBreakdown: 'Dépenses par Fournisseur',
    vendorBreakdownDesc: 'Charges d\'exploitation par fournisseur.',
    recentTransactions: 'Transactions Récentes',
    recentTransactionsDesc: 'Dernières écritures du grand livre.',
    aggregating: 'Agrégation des données et compilation...',
    failedDashboard: 'Échec du Chargement',
    retryConnection: 'Réessayer',
    financialLedger: 'Grands Livres Financiers',
    financialsDesc: 'Suivi des charges, reçus fournisseurs et ventes.',
    addCharge: 'Ajouter une Charge',
    logRevenue: 'Enregistrer un Revenu',
    tabCharges: 'Charges d\'Exploitation',
    tabRevenue: 'Flux de Revenus',
    ledgerTotal: 'Total du Grand Livre',
    ledgerTotalDesc: 'Somme de tous les éléments correspondant aux filtres.',
    searchFilters: 'Filtres de Recherche',
    clearAll: 'Tout Effacer',
    category: 'Catégorie',
    allCategories: 'Toutes Catégories',
    allSources: 'Toutes Sources',
    fuelVendor: 'Fournisseur',
    allSuppliers: 'Tous Fournisseurs',
    startDate: 'Date de Début',
    endDate: 'Date de Fin',
    date: 'Date',
    supplierVendor: 'Fournisseur',
    description: 'Description',
    flowType: 'Type',
    amount: 'Montant (MAD / DH)',
    actions: 'Actions',
    ocrScan: 'Numérisation OCR',
    manual: 'Manuel',
    salesInflow: 'Entrée de Ventes',
    noCharges: 'Aucune charge correspondante.',
    noRevenue: 'Aucun revenu correspondant.',
    retrieving: 'Récupération du grand livre...',
    recordCharge: 'Enregistrer une Charge',
    logRevenueStream: 'Enregistrer un Revenu',
    editEntry: 'Modifier l\'Écriture',
    valueAmount: 'Montant (MAD / DH)',
    transactionDate: 'Date de Transaction',
    categoryClassification: 'Classification',
    selectCategory: 'Choisir Catégorie...',
    selectStream: 'Choisir Flux...',
    supplierMapping: 'Fournisseur',
    chooseSupplier: 'Choisir Fournisseur...',
    notesRemarks: 'Notes / Remarques',
    notesPlaceholder: 'Notes de référence...',
    cancel: 'Annuler',
    confirmEntry: 'Confirmer',
    save: 'Enregistrer',
    deleteConfirm: 'Supprimer définitivement cette écriture?',
    staffPayroll: 'Personnel & Paie',
    staffDesc: 'Gérer le personnel, CIN et paiements.',
    addStaff: 'Ajouter Personnel',
    logPayment: 'Enregistrer Paiement',
    roster: 'Effectif de la Station',
    payroll: 'Paie',
    name: 'Nom',
    cin: 'CIN',
    position: 'Poste',
    phone: 'Téléphone',
    status: 'Statut',
    active: 'Actif',
    inactive: 'Inactif',
    fullName: 'Nom Complet',
    cinLabel: 'CIN (Carte d\'Identité)',
    hireDate: 'Date d\'Embauche',
    modifyStaff: 'Modifier le Profil',
    registerStaff: 'Enregistrer Personnel',
    selectWorker: 'Choisir Employé',
    selectPosition: 'Choisir...',
    pumpAttendant: 'Pompiste',
    cashier: 'Caissier',
    technician: 'Technicien',
    paymentAmount: 'Montant (MAD / DH)',
    paymentDate: 'Date de Paiement',
    paymentNotes: 'Notes',
    paymentNotesPlaceholder: 'Paie hebdo, heures sup, bonus...',
    logSalaryPayment: 'Enregistrer Salaire',
    logPaymentBtn: 'Enregistrer',
    noPayments: 'Aucun paiement enregistré.',
    deletePaymentConfirm: 'Supprimer ce paiement et sa charge liée?',
    reviewQueueTitle: 'File de Révision des Reçus',
    reviewQueueDesc: 'Auditer les numérisations à faible confiance avant classement.',
    loadingQueue: 'Chargement de la file de révision...',
    queueClear: 'File Vide!',
    queueClearDesc: 'Tous les reçus sont résolus et classés.',
    pendingTickets: 'Tickets en Attente',
    unknownVendor: 'Fournisseur Inconnu',
    matchPct: '% Correspondance',
    uploaded: 'Téléversé',
    amountNA: 'Montant: N/A',
    auditForm: 'Formulaire de Révision',
    auditFormDesc: 'Réconcilier les extractions OCR avec la preuve visuelle.',
    verifyAmount: 'Vérifier le Montant (MAD / DH)',
    assignVendor: 'Assigner Fournisseur',
    unassigned: 'Non assigné (Définir...)',
    receiptDate: 'Date du Reçu',
    filingCategory: 'Catégorie de Classement',
    reject: 'Rejeter',
    approveLedger: 'Approuver',
    receiptEntry: 'Saisie de Reçu',
    aiScan: 'Numérisation IA',
    manualEntry: 'Saisie Manuelle',
    scanning: 'Vertex AI lit le reçu...',
    scanningDesc: 'Extraction fournisseur, totaux et date via Gemini 2.5 Flash',
    useCamera: 'Utiliser Caméra',
    analyzeAI: 'Analyser avec IA',
    dragDrop: 'Glisser-déposer ou cliquer pour parcourir',
    fileTypes: 'PNG, JPG, WEBP, PDF (Max 10MB)',
    vendor: 'Fournisseur',
    selectVendor: 'Choisir fournisseur...',
    addAnother: 'Ajouter Autre',
    entryFailed: 'Échec de la Saisie',
    tryAgain: 'Réessayer',
    filedSuccess: 'Classé avec Succès!',
    sentToReview: 'Envoyé en Révision',
    fileReceipt: 'Classer le Reçu',
    filing: 'Classement...',
    receiptImage: 'Image du Reçu (Optionnel)',
    amountDateRequired: 'Le montant et la date sont requis.',
    cameraFailed: 'Caméra inaccessible. Veuillez téléverser une image.',
    verifyAndFile: 'Vérifier & Classer',
    // Sold Gas
    soldGasDesc: 'Téléversez plusieurs reçus de vente, laissez l\'IA lire montant/date/fournisseur, puis approuvez chacun pour enregistrer comme revenu.',
    processingReceipts: 'L\'IA lit vos reçus...',
    soldGasDrop: 'Glissez-déposez plusieurs reçus ou cliquez pour sélectionner',
    soldGasFileTypes: 'PNG, JPG, WEBP, PDF — Jusqu\'à 20 (Max 10MB chacun)',
    receiptsSelected: 'reçus sélectionnés',
    scanAll: 'Tout Scanner',
    processedOk: 'scannés avec succès',
    processedFailed: 'échoués',
    soldGasQueueClear: 'Aucun Reçu à Approuver',
    soldGasQueueClearDesc: 'Téléversez des reçus ci-dessus. Après lecture IA, approuvez chacun pour enregistrer comme ventes.',
    reviewing: 'Révision',
    of: 'sur',
    approveSoldGas: 'Approuver & Suivant',
    soldGasApproveTitle: 'Approuver le Reçu de Vente',
    soldGasApproveDesc: 'Vérifiez le montant, la date et le fournisseur extraits, puis approuvez pour enregistrer.',
    ocrResults: 'Données OCR Extraites',
    ocrResultsDesc: 'Vérifier et corriger les champs extraits, puis classer.',
    confirmFile: 'Confirmer & Classer',
    savePending: 'Enregistrer pour Révision',
    confidence: 'Confiance',
    exportTitle: 'Exporter le Relevé Financier',
    exportFormat: 'Format d\'Export',
    microsoftExcel: 'Microsoft Excel',
    pdfStatement: 'Relevé PDF',
    exportScope: 'Portée d\'Export',
    combinedStatement: 'Relevé Complet (Tableau + Revenus + Charges + Reçus)',
    revenueOnly: 'Grand Livre des Revenus Uniquement',
    chargesOnly: 'Charges d\'Exploitation Uniquement',
    receiptsOnly: 'Journaux de Reçus Uniquement',
    timeInterval: 'Intervalle',
    custom: 'Personnalisé',
    customDatesRequired: 'Veuillez spécifier les dates de début et fin.',
    exportFailed: 'Échec du téléchargement. Réessayer.',
    generating: 'Génération...',
    exportTo: 'Exporter en',
    vendorFilter: 'Filtre Fournisseur',
    categoryFilter: 'Filtre Catégorie',
    allVendors: 'Tous Fournisseurs',
    loading: 'Chargement...',
  },
  ar: {
    brandName: 'محطة المحيط للمحروقات',
    brandTagline: 'بوابة العمليات',
    dashboard: 'لوحة التحكم',
    financials: 'الدفتر المالي',
    staff: 'الموظفين والرواتب',
    reviewQueue: 'قائمة المراجعة',
    soldGas: 'المبيعات',
    logout: 'تسجيل الخروج',
    loginTitle: 'تسجيل الدخول',
    loginSubtitle: 'بوابة إدارة المحطة',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    signIn: 'دخول',
    authorizedOnly: 'للموظفين المصرح لهم فقط',
    fillCredentials: 'يرجى ملء جميع الحقول.',
    invalidCredentials: 'بريد إلكتروني أو كلمة مرور غير صحيحة.',
    execDashboard: 'لوحة التحكم التنفيذية',
    dashboardDesc: 'نظرة تشغيلية مباشرة وتحليلات مالية ومقارنات.',
    smartScan: 'مسح ذكي',
    exportData: 'تصدير',
    reviewRequired: 'مراجعة المستندات مطلوبة',
    reviewRequiredDesc: 'يوجد {n} إيصال منخفض الثقة بانتظار التحقق.',
    resolveQueue: 'حل القائمة',
    weekView: 'أسبوع',
    monthView: 'شهر',
    yearView: 'سنة',
    refresh: 'تحديث',
    totalRevenue: 'إجمالي الإيرادات',
    totalSpend: 'إجمالي المصروفات',
    netProfit: 'صافي الربح',
    receiptsSales: '+ إيصالات ومبيعات',
    chargesLogistics: '- مصاريف ولوجستيك',
    surplus: 'فائض مسجل',
    deficit: 'عجز تشغيلي',
    trendTitle: 'اتجاه الإيرادات مقابل المصروفات',
    trendDesc: 'تدفق زمني يقارن الإيرادات بالمصروفات.',
    noHistory: 'لا توجد إدخالات في هذه الفترة.',
    revenueDist: 'توزيع مصادر الإيرادات',
    revenueDistDesc: 'تفصيل الأرباح حسب الفئة.',
    noRevenueData: 'لا توجد بيانات إيرادات.',
    expenseDist: 'توزيع فئات المصروفات',
    expenseDistDesc: 'تصنيف مصروفات الدفتر.',
    noExpenseData: 'لا توجد مصروفات تشغيلية.',
    vendorBreakdown: 'مصروفات حسب المورد',
    vendorBreakdownDesc: 'المصروفات التشغيلية حسب مورد الوقود.',
    recentTransactions: 'أحدث المعاملات',
    recentTransactionsDesc: 'أحدث الإدخالات في الدفتر.',
    aggregating: 'تجميع السجلات وتحليل البيانات...',
    failedDashboard: 'فشل تحميل لوحة التحكم',
    retryConnection: 'إعادة الاتصال',
    financialLedger: 'الدفاتر المالية',
    financialsDesc: 'تتبع المصروفات وإيصالات الموردين والمبيعات.',
    addCharge: 'إضافة مصروف',
    logRevenue: 'تسجيل إيراد',
    tabCharges: 'المصروفات التشغيلية',
    tabRevenue: 'مصادر الإيرادات',
    ledgerTotal: 'إجمالي الدفتر الحالي',
    ledgerTotalDesc: 'مجموع جميع العناصر المطابقة للفلاتر.',
    searchFilters: 'فلاتر البحث',
    clearAll: 'مسح الكل',
    category: 'الفئة',
    allCategories: 'كل الفئات',
    allSources: 'كل المصادر',
    fuelVendor: 'مورد الوقود',
    allSuppliers: 'كل الموردين',
    startDate: 'تاريخ البداية',
    endDate: 'تاريخ النهاية',
    date: 'التاريخ',
    supplierVendor: 'المورد',
    description: 'الوصف',
    flowType: 'النوع',
    amount: 'المبلغ (درهم)',
    actions: 'إجراءات',
    ocrScan: 'مسح OCR',
    manual: 'يدوي',
    salesInflow: 'إيرادات مبيعات',
    noCharges: 'لا توجد مصروفات مطابقة.',
    noRevenue: 'لا توجد إيرادات مطابقة.',
    retrieving: 'جاري استرجاع الدفتر...',
    recordCharge: 'تسجيل مصروف',
    logRevenueStream: 'تسجيل إيراد يومي',
    editEntry: 'تعديل الإدخال',
    valueAmount: 'المبلغ (درهم)',
    transactionDate: 'تاريخ المعاملة',
    categoryClassification: 'تصنيف الفئة',
    selectCategory: 'اختر الفئة...',
    selectStream: 'اختر المصدر...',
    supplierMapping: 'تعيين المورد',
    chooseSupplier: 'اختر المورد...',
    notesRemarks: 'ملاحظات',
    notesPlaceholder: 'ملاحظات الفاتورة/المعاملة...',
    cancel: 'إلغاء',
    confirmEntry: 'تأكيد',
    save: 'حفظ',
    deleteConfirm: 'هل أنت متأكد من حذف هذا السجل نهائياً؟',
    staffPayroll: 'الموظفين والرواتب',
    staffDesc: 'إدارة موظفي المحطة وبطاقات الهوية والرواتب.',
    addStaff: 'إضافة موظف',
    logPayment: 'تسجيل دفعة',
    roster: 'كشف الموظفين',
    payroll: 'الرواتب',
    name: 'الاسم',
    cin: 'بطاقة التعريف',
    position: 'المنصب',
    phone: 'الهاتف',
    status: 'الحالة',
    active: 'نشط',
    inactive: 'غير نشط',
    fullName: 'الاسم الكامل',
    cinLabel: 'بطاقة التعريف الوطنية',
    hireDate: 'تاريخ التوظيف',
    modifyStaff: 'تعديل ملف الموظف',
    registerStaff: 'تسجيل موظف جديد',
    selectWorker: 'اختر موظف',
    selectPosition: 'اختر...',
    pumpAttendant: 'عامل مضخة',
    cashier: 'أمين الصندوق',
    technician: 'فني',
    paymentAmount: 'المبلغ (درهم)',
    paymentDate: 'تاريخ الدفعة',
    paymentNotes: 'ملاحظات',
    paymentNotesPlaceholder: 'راتب أسبوعي، إضافي، مكافأة...',
    logSalaryPayment: 'تسجيل راتب',
    logPaymentBtn: 'تسجيل',
    noPayments: 'لا توجد دفعات.',
    deletePaymentConfirm: 'حذف هذه الدفعة والمصروف المرتبط بها؟',
    reviewQueueTitle: 'قائمة مراجعة الإيصالات',
    reviewQueueDesc: 'مراجعة المسحات منخفضة الثقة قبل تسجيلها.',
    loadingQueue: 'جاري تحميل قائمة المراجعة...',
    queueClear: 'القائمة فارغة!',
    queueClearDesc: 'تم حل جميع الإيصالات وتصنيفها.',
    pendingTickets: 'تذاكر معلقة',
    unknownVendor: 'مورد غير معروف',
    matchPct: '% تطابق',
    uploaded: 'تم الرفع',
    amountNA: 'المبلغ: غير متوفر',
    auditForm: 'نموذج التدقيق',
    auditFormDesc: 'مطابقة استخراج OCR مع الإثبات المرئي.',
    verifyAmount: 'تحقق من المبلغ (درهم)',
    assignVendor: 'تعيين مورد',
    unassigned: 'غير معين (حدد المورد...)',
    receiptDate: 'تاريخ الإيصال',
    filingCategory: 'فئة التصنيف',
    reject: 'رفض',
    approveLedger: 'موافقة وتسجيل',
    receiptEntry: 'إدخال إيصال',
    aiScan: 'مسح ذكي',
    manualEntry: 'إدخال يدوي',
    scanning: 'Vertex AI يقرأ الإيصال...',
    scanningDesc: 'استخراج المورد والمجموع والتاريخ عبر Gemini 2.5 Flash',
    useCamera: 'استخدم الكاميرا',
    analyzeAI: 'تحليل بالذكاء الاصطناعي',
    dragDrop: 'اسحب وأفلت الإيصال أو انقر للتصفح',
    fileTypes: 'PNG, JPG, WEBP, PDF (الحد 10MB)',
    vendor: 'المورد',
    selectVendor: 'اختر المورد...',
    addAnother: 'إضافة آخر',
    entryFailed: 'فشل الإدخال',
    tryAgain: 'حاول مرة أخرى',
    filedSuccess: 'تم التسجيل بنجاح!',
    sentToReview: 'أُرسل للمراجعة',
    fileReceipt: 'تسجيل الإيصال',
    filing: 'جاري التسجيل...',
    receiptImage: 'صورة الإيصال (اختياري)',
    amountDateRequired: 'المبلغ والتاريخ مطلوبان.',
    cameraFailed: 'تعذر الوصول للكاميرا. يرجى رفع صورة.',
    verifyAndFile: 'تحقق وتسجيل',
    // Sold Gas
    soldGasDesc: 'ارفع عدة إيصالات مبيعات، دع الذكاء الاصطناعي يقرأ المبلغ/التاريخ/المورد، ثم وافق على كل واحد لتسجيله كإيراد مبيعات وقود.',
    processingReceipts: 'الذكاء الاصطناعي يقرأ إيصالاتك...',
    soldGasDrop: 'اسحب وأفلت عدة إيصالات أو انقر للاختيار من المعرض',
    soldGasFileTypes: 'PNG, JPG, WEBP, PDF — حتى 20 (الحد 10MB لكل واحد)',
    receiptsSelected: 'إيصالات محددة',
    scanAll: 'مسح الكل',
    processedOk: 'تم مسحها بنجاح',
    processedFailed: 'فشلت',
    soldGasQueueClear: 'لا توجد إيصالات للموافقة',
    soldGasQueueClearDesc: 'ارفع إيصالات المبيعات بالأعلى. بعد قراءة الذكاء الاصطناعي، وافق على كل واحد لتسجيله كمبيعات وقود.',
    reviewing: 'مراجعة',
    of: 'من',
    approveSoldGas: 'موافقة والتالي',
    soldGasApproveTitle: 'الموافقة على إيصال البيع',
    soldGasApproveDesc: 'تحقق من المبلغ والتاريخ والمورد المستخرجين، ثم وافق لتسجيله كإيراد مبيعات وقود.',
    ocrResults: 'بيانات OCR المستخرجة',
    ocrResultsDesc: 'راجع وصحح الحقول المستخرجة ثم سجلها.',
    confirmFile: 'تأكيد وتسجيل',
    savePending: 'حفظ للمراجعة',
    confidence: 'الثقة',
    exportTitle: 'تصدير البيان المالي',
    exportFormat: 'تنسيق التصدير',
    microsoftExcel: 'مايكروسوفت إكسل',
    pdfStatement: 'بيان PDF',
    exportScope: 'نطاق التصدير',
    combinedStatement: 'بيان شامل (لوحة + إيرادات + مصروفات + إيصالات)',
    revenueOnly: 'دفتر الإيرادات فقط',
    chargesOnly: 'المصروفات التشغيلية فقط',
    receiptsOnly: 'سجلات الإيصالات فقط',
    timeInterval: 'الفاصل الزمني',
    custom: 'مخصص',
    customDatesRequired: 'يرجى تحديد تاريخ البداية والنهاية.',
    exportFailed: 'فشل التنزيل. حاول مرة أخرى.',
    generating: 'جاري الإنشاء...',
    exportTo: 'تصدير إلى',
    vendorFilter: 'فلتر المورد',
    categoryFilter: 'فلتر الفئة',
    allVendors: 'كل الموردين',
    loading: 'جاري التحميل...',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('almohit_lang');
    return saved && t[saved] ? saved : 'en';
  });

  const dir = languages[lang].dir;

  useEffect(() => {
    localStorage.setItem('almohit_lang', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = languages[lang].dir;
  }, [lang, dir]);

  const changeLanguage = useCallback((code) => {
    if (t[code]) setLang(code);
  }, []);

  const tr = useCallback((key, vars) => {
    let str = (t[lang] && t[lang][key]) || t.en[key] || key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replace(`{${k}}`, v);
      });
    }
    return str;
  }, [lang]);

  const catLabel = useCallback((cat) => {
    return (categoryLabels[lang] && categoryLabels[lang][cat]) || categoryLabels.en[cat] || cat;
  }, [lang]);

  const value = { lang, dir, changeLanguage, t: tr, catLabel };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    return {
      lang: 'en',
      dir: 'ltr',
      changeLanguage: () => {},
      t: (k) => k,
      catLabel: (c) => c,
    };
  }
  return ctx;
}
